# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: AGI SEEKING
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  探索通用人工智能前沿技术与最佳实践，分享大模型理论与落地经验。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://huge-stone.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  huge-stone

# 添加页面集合配置
include: ["_pages"]

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# 标签和分类设置
permalink: /:year/:month/:day/:title/

# 确保GitHub Pages能正确处理
markdown: kramdown

# 自定义导航链接
header_pages:
  - _pages/tutorials.md
  - _pages/tags.md
  - _pages/projects.md
  - _pages/resources.md
  - _pages/code-showcase.md
  - _pages/code-example.md
  - _pages/code-sample.md
  - _pages/search.md

# 排除不需要的文件
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# 添加Disqus评论系统配置
# 如果您没有注册Disqus或不需要评论功能，请删除或注释掉以下内容
# disqus:
#   shortname: huge-stone-blog # 替换为您在Disqus上注册的shortname

# 添加Google Analytics配置
google_analytics: G-XXXXXXXXXX # 替换为您的Google Analytics跟踪ID
